apiVersion: v1
kind: Service
metadata:
  labels:
    app: maesh
    component: grafana
    release: maesh
  name: grafana
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
    component: core
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
