apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: maesh
    component: prometheus
    release: maesh
  name: prometheus
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: webui
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    component: core
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
