apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  generation: 1
  labels:
    app: maesh
    release: maesh
  name: prometheus
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: prometheus
      component: core
status:
  currentHealthy: 0
  desiredHealthy: 0
  disruptionsAllowed: 0
  expectedPods: 0
