apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/name: jaeger
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
      app.kubernetes.io/component: all-in-one
      app.kubernetes.io/name: jaeger
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/port: "16686"
        prometheus.io/scrape: "true"
      labels:
        app: jaeger
        app.kubernetes.io/component: all-in-one
        app.kubernetes.io/name: jaeger
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        image: jaegertracing/all-in-one:1.13
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: readiness
          timeoutSeconds: 1
        name: jaeger
        ports:
        - containerPort: 5775
          name: thrift-legacy
          protocol: UDP
        - containerPort: 6831
          name: compact-thrift
          protocol: UDP
        - containerPort: 6832
          name: binary-thrift
          protocol: UDP
        - containerPort: 5778
          name: serve-configs
          protocol: TCP
        - containerPort: 9411
          name: collector-zip
          protocol: TCP
        - containerPort: 14267
          name: collector-tch
          protocol: TCP
        - containerPort: 14268
          name: collector-http
          protocol: TCP
        - containerPort: 14269
          name: readiness
          protocol: TCP
        - containerPort: 16686
          name: serve-frontend
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: readiness
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      serviceAccount: jaeger
      serviceAccountName: jaeger
      terminationGracePeriodSeconds: 30
