apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  generation: 1
  labels:
    app: maesh
    release: maesh
  name: maesh-mesh
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: maesh
      component: maesh-mesh
      release: maesh
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: maesh
        component: maesh-mesh
        release: maesh
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        - --entryPoints.readiness.address=:1081
        - --entryPoints.http-5000.address=:5000
        - --entryPoints.http-5001.address=:5001
        - --entryPoints.http-5002.address=:5002
        - --entryPoints.http-5003.address=:5003
        - --entryPoints.http-5004.address=:5004
        - --entryPoints.http-5005.address=:5005
        - --entryPoints.http-5006.address=:5006
        - --entryPoints.http-5007.address=:5007
        - --entryPoints.http-5008.address=:5008
        - --entryPoints.http-5009.address=:5009
        - --entryPoints.tcp-10000.address=:10000
        - --entryPoints.tcp-10001.address=:10001
        - --entryPoints.tcp-10002.address=:10002
        - --entryPoints.tcp-10003.address=:10003
        - --entryPoints.tcp-10004.address=:10004
        - --entryPoints.tcp-10005.address=:10005
        - --entryPoints.tcp-10006.address=:10006
        - --entryPoints.tcp-10007.address=:10007
        - --entryPoints.tcp-10008.address=:10008
        - --entryPoints.tcp-10009.address=:10009
        - --entryPoints.tcp-10010.address=:10010
        - --entryPoints.tcp-10011.address=:10011
        - --entryPoints.tcp-10012.address=:10012
        - --entryPoints.tcp-10013.address=:10013
        - --entryPoints.tcp-10014.address=:10014
        - --entryPoints.tcp-10015.address=:10015
        - --entryPoints.tcp-10016.address=:10016
        - --entryPoints.tcp-10017.address=:10017
        - --entryPoints.tcp-10018.address=:10018
        - --entryPoints.tcp-10019.address=:10019
        - --entryPoints.tcp-10020.address=:10020
        - --entryPoints.tcp-10021.address=:10021
        - --entryPoints.tcp-10022.address=:10022
        - --entryPoints.tcp-10023.address=:10023
        - --entryPoints.tcp-10024.address=:10024
        - --providers.rest
        - --providers.rest.insecure
        - --tracing.jaeger.localagenthostport=jaeger-agent.maesh.svc.cluster.local:6831
        - --tracing.jaeger.samplingserverurl=http://jaeger-agent.maesh.svc.cluster.local:5778/sampling
        - --api.dashboard
        - --api.insecure
        - --ping
        - --log.level=INFO
        - --metrics.prometheus
        image: traefik:v2.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 1
          successThreshold: 1
          tcpSocket:
            port: liveness
          timeoutSeconds: 1
        name: maesh-mesh
        ports:
        - containerPort: 1081
          name: readiness
          protocol: TCP
        - containerPort: 10000
          name: liveness
          protocol: TCP
        - containerPort: 8080
          name: api
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: readiness
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      serviceAccount: maesh-mesh
      serviceAccountName: maesh-mesh
      terminationGracePeriodSeconds: 30
  templateGeneration: 1
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
