apiVersion: v1
data:
  prometheus.yaml: |
    global:
      scrape_interval: 10s
      scrape_timeout: 10s
      evaluation_interval: 10s
    rule_files:
      - "/prometheus/rules/*.yaml"

    scrape_configs:
      - job_name: 'maesh'
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
            # Add the version label extracted from the pod label version.
          - source_labels: [__meta_kubernetes_pod_label_version]
            action: replace
            replacement: $1
            target_label: version
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - maesh
kind: ConfigMap
metadata:
  labels:
    app: maesh
    component: prometheus
    release: maesh
  name: prometheus-core
