apiVersion: v1
data:
  general.yaml: |
    groups:
      - name: general
        rules:
          - record: job:http_duration_seconds:p99:5m
            expr: histogram_quantile(0.99, sum(rate(http_duration_seconds_bucket[5m])) by (job, le))
          - record: job:http_duration_seconds:p90:5m
            expr: histogram_quantile(0.90, sum(rate(http_duration_seconds_bucket[5m])) by (job, le))
          - record: job:http_duration_seconds:p50:5m
            expr: histogram_quantile(0.50, sum(rate(http_duration_seconds_bucket[5m])) by (job, le))
kind: ConfigMap
metadata:
  labels:
    app: maesh
    component: prometheus
    release: maesh
  name: prometheus-rules
